# Generated by Django 4.2.3 on 2023-09-04 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='slocation',
            new_name='sclocation',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='sname',
            new_name='scname',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='sprincipal',
            new_name='scprincipal',
        ),
    ]
